name: dizonli_app
description: "Application de suivi de pas et défis sportifs avec intégration sociale"
publish_to: 'none'
version: 1.0.0-beta+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Design
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: any
  google_fonts: ^6.2.1
  fl_chart: ^0.65.0
  lottie: ^2.7.0
  
  # Firebase (Auth, Firestore, Messaging)
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_messaging: ^15.2.10
  
  # Cloudinary (Image Storage)
  cloudinary_public: ^0.21.0
  
  # State Management
  provider: ^6.1.2
  
  # Local Storage
  shared_preferences: ^2.3.5
  
  # Utils
  uuid: ^4.5.1
  screenshot: ^3.0.0
  share_plus: ^7.2.2
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  image_cropper: ^8.0.2
  
  # Health & Sensors
  pedometer: ^4.0.2
  health: ^13.2.0
  permission_handler: ^11.4.0
  
  # Notifications
  flutter_local_notifications: ^17.2.3
  
  # Navigation
  go_router: ^12.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#4CAF50"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"
  min_sdk_android: 26

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
    - assets/animations/
