/// Liste des pays et leurs villes principales
class CountriesCities {
  static final Map<String, List<String>> data = {
    // Afrique
    'Bénin': [
      'Cotonou',
      'Porto-Novo',
      'Parakou',
      'Abomey-Calavi',
      'Djougou',
      'Bohicon',
      'Kandi',
      'Lokossa',
      'Ouidah',
      'Abomey',
      'Natitingou',
      'Savé',
      'Malanville',
      'Pobé',
      'Kétou',
    ],
    'Nigéria': [
      'Lagos',
      'Abuja',
      'Kano',
      'Ibadan',
      'Port Harcourt',
      'Benin City',
      'Kaduna',
      'Maiduguri',
      'Zaria',
      'Jos',
    ],
    'Togo': [
      'Lomé',
      'Sokodé',
      'Kara',
      'Kpalimé',
      'Atakpamé',
      'Dapaong',
      'Tsévié',
      'Aného',
      'Vogan',
      'Bassar',
    ],
    'Côte d\'Ivoire': [
      'Abidjan',
      'Yamoussoukro',
      'Bouaké',
      'Daloa',
      'San-Pédro',
      'Korhogo',
      'Man',
      'Divo',
      'Gagnoa',
      'Abengourou',
    ],
    'Ghana': [
      'Accra',
      'Kumasi',
      'Tamale',
      'Takoradi',
      'Ashaiman',
      'Sunyani',
      'Cape Coast',
      'Obuasi',
      'Teshie',
      'Tema',
    ],
    'Sénégal': [
      'Dakar',
      'Touba',
      'Thiès',
      'Saint-Louis',
      'Kaolack',
      'Mbour',
      'Ziguinchor',
      'Louga',
      'Rufisque',
      'Diourbel',
    ],
    'Cameroun': [
      'Douala',
      'Yaoundé',
      'Garoua',
      'Bamenda',
      'Bafoussam',
      'Maroua',
      'Nkongsamba',
      'Ngaoundéré',
      'Bertoua',
      'Édéa',
    ],
    'Mali': [
      'Bamako',
      'Sikasso',
      'Mopti',
      'Koutiala',
      'Kayes',
      'Ségou',
      'Gao',
      'Kati',
      'Tombouctou',
      'Markala',
    ],
    'Burkina Faso': [
      'Ouagadougou',
      'Bobo-Dioulasso',
      'Koudougou',
      'Ouahigouya',
      'Banfora',
      'Dédougou',
      'Kaya',
      'Fada N\'gourma',
      'Tenkodogo',
      'Houndé',
    ],
    'Niger': [
      'Niamey',
      'Zinder',
      'Maradi',
      'Agadez',
      'Tahoua',
      'Dosso',
      'Diffa',
      'Arlit',
      'Tillabéri',
      'Tessaoua',
    ],
    'Gabon': [
      'Libreville',
      'Port-Gentil',
      'Franceville',
      'Oyem',
      'Moanda',
      'Mouila',
      'Lambaréné',
      'Tchibanga',
      'Koulamoutou',
      'Makokou',
    ],
    'Congo': [
      'Brazzaville',
      'Pointe-Noire',
      'Dolisie',
      'Nkayi',
      'Mossendjo',
      'Owando',
      'Ouesso',
      'Madingou',
      'Gamboma',
      'Impfondo',
    ],
    'RD Congo': [
      'Kinshasa',
      'Lubumbashi',
      'Mbuji-Mayi',
      'Kananga',
      'Kisangani',
      'Goma',
      'Bukavu',
      'Likasi',
      'Kolwezi',
      'Matadi',
    ],
    
    // Europe
    'France': [
      'Paris',
      'Marseille',
      'Lyon',
      'Toulouse',
      'Nice',
      'Nantes',
      'Strasbourg',
      'Montpellier',
      'Bordeaux',
      'Lille',
      'Rennes',
      'Reims',
      'Le Havre',
      'Saint-Étienne',
      'Toulon',
    ],
    'Belgique': [
      'Bruxelles',
      'Anvers',
      'Gand',
      'Charleroi',
      'Liège',
      'Bruges',
      'Namur',
      'Louvain',
      'Mons',
      'Alost',
    ],
    'Suisse': [
      'Zurich',
      'Genève',
      'Bâle',
      'Lausanne',
      'Berne',
      'Winterthour',
      'Lucerne',
      'Saint-Gall',
      'Lugano',
      'Bienne',
    ],
    'Canada': [
      'Toronto',
      'Montreal',
      'Vancouver',
      'Calgary',
      'Edmonton',
      'Ottawa',
      'Winnipeg',
      'Quebec',
      'Hamilton',
      'Kitchener',
    ],
    'États-Unis': [
      'New York',
      'Los Angeles',
      'Chicago',
      'Houston',
      'Phoenix',
      'Philadelphia',
      'San Antonio',
      'San Diego',
      'Dallas',
      'San Jose',
    ],
  };

  static List<String> get countries {
    final sortedCountries = data.keys.toList()..sort();
    return sortedCountries;
  }

  static List<String> getCities(String country) {
    return data[country] ?? [];
  }
}

